/*
 *	dc_maple.c -- which KallistiOS subsystems start up, and one that does not.
 *
 *	CONFIRMED ON HARDWARE: with a rumble pack fitted the game never gets past the
 *	Sega licence screen; without it, it boots normally. That is long before any of
 *	our code draws anything.
 *
 *	The cause is KOS's initial bus scan, in
 *	kernel/arch/dreamcast/hardware/maple/maple_init_shutdown.c:
 *
 *	    static int maple_scan_done(maple_state_t *state) {
 *	        return state->scan_ready_mask == 0xf;
 *	    }
 *
 *	    void maple_wait_scan(void) {
 *	        thd_poll((thd_cb_t)maple_scan_done, &maple_state, 0);
 *
 *	It waits for all four ports to report. `thd_poll` with a timeout of 0 sets
 *	`wait_timeout = 0` and blocks with no deadline (kernel/thread/thread.c:956),
 *	so it is a wait with no way out. The pack makes one port never report.
 *
 *	Two pieces of evidence settle it. b21 cleared INIT_PURUPURU, so the rumble
 *	driver never initialised, and it still hung -- which exonerates the driver.
 *	And Max found that pulling the pack out *while hung* lets the boot continue,
 *	which is precisely a blocking wait releasing when the offending device leaves
 *	the bus.
 *
 *	WHY THIS FILE IS NO LONGER ONE LINE
 *
 *	The previous note here concluded that bounding the wait was not available to
 *	us, because `maple_wait_scan` is gated on INIT_MAPLE_ALL alongside
 *	`maple_init` itself, so clearing the flag would take the controller too.
 *
 *	That is true of the flag and false of the mechanism. INIT_MAPLE_ALL is the OR
 *	of eight peripheral flags and the gate is a bitwise AND, so no combination of
 *	flags separates the scan from the driver. But KOS_INIT_FLAGS() does nothing
 *	except *define variables*: for each subsystem it emits
 *
 *	    void (*func##_weak)(void) = ((flags) & (mask)) ? func : NULL;
 *
 *	and init.c later calls whatever the pointer holds. So the list below is
 *	KOS's own, generated from arch/init_flags.h and kos/init.h so it cannot
 *	drift, with exactly one line omitted -- and `maple_wait_scan_weak` defined
 *	NULL by hand instead. Every other subsystem, INIT_PURUPURU included, starts
 *	exactly as before.
 *
 *	WHAT REPLACES THE WAIT
 *
 *	`dc_maple_wait_scan_bounded` waits on exactly the condition KOS waits on, with
 *	a deadline. A normal boot is therefore unchanged -- the scan finishes in a few
 *	frames and the wait returns -- while a device that never reports costs the
 *	timeout rather than the console.
 *
 *	Regenerate the list with tools/gen-maple-flags.py after a KOS update.
 */

#include <kos/init.h>
#include <dc/maple.h>
#include <dc/maple/controller.h>
#include <arch/timer.h>
#include <kos/thread.h>

#define OUR_FLAGS	INIT_DEFAULT

	/* GENERATED by tools/gen-maple-flags.py -- do not hand-edit. */
	const uint32_t __kos_init_flags = (OUR_FLAGS);
	KOS_INIT_FLAG(OUR_FLAGS, INIT_NET, arch_init_net);
	KOS_INIT_FLAG(OUR_FLAGS, INIT_NET, net_shutdown);
	KOS_INIT_FLAG(OUR_FLAGS, INIT_NET, eth_init);
	KOS_INIT_FLAG(OUR_FLAGS, INIT_NET, eth_shutdown);
	KOS_INIT_FLAG(OUR_FLAGS, INIT_FS_ALL, fs_init);
	KOS_INIT_FLAG(OUR_FLAGS, INIT_FS_ALL, fs_shutdown);
	KOS_INIT_FLAG(OUR_FLAGS, INIT_FS_ROMDISK, fs_romdisk_init);
	KOS_INIT_FLAG(OUR_FLAGS, INIT_FS_ROMDISK, fs_romdisk_shutdown);
	KOS_INIT_FLAG(OUR_FLAGS, INIT_FS_NULL, fs_null_init);
	KOS_INIT_FLAG(OUR_FLAGS, INIT_FS_NULL, fs_null_shutdown);
	KOS_INIT_FLAG(OUR_FLAGS, INIT_FS_PTY, fs_pty_init);
	KOS_INIT_FLAG(OUR_FLAGS, INIT_FS_PTY, fs_pty_shutdown);
	KOS_INIT_FLAG(OUR_FLAGS, INIT_FS_RAMDISK, fs_ramdisk_init);
	KOS_INIT_FLAG(OUR_FLAGS, INIT_FS_RAMDISK, fs_ramdisk_shutdown);
	KOS_INIT_FLAG(OUR_FLAGS, INIT_FS_RND, fs_rnd_init);
	KOS_INIT_FLAG(OUR_FLAGS, INIT_FS_RND, fs_rnd_shutdown);
	KOS_INIT_FLAG(OUR_FLAGS, INIT_FS_DEV, fs_dev_init);
	KOS_INIT_FLAG(OUR_FLAGS, INIT_FS_DEV, fs_dev_shutdown);
	KOS_INIT_FLAG(OUR_FLAGS, INIT_EXPORT, export_init);
	KOS_INIT_FLAG(OUR_FLAGS, INIT_LIBRARY, library_init);
	KOS_INIT_FLAG(OUR_FLAGS, INIT_LIBRARY, library_shutdown);
	KOS_INIT_FLAG_NONE(OUR_FLAGS, INIT_NO_SHUTDOWN, kos_shutdown);
	KOS_INIT_FLAG_NONE(OUR_FLAGS, INIT_NO_DCLOAD, dcload_init);
	KOS_INIT_FLAG_NONE(OUR_FLAGS, INIT_NO_DCLOAD, fs_dcload_init_console);
	KOS_INIT_FLAG_NONE(OUR_FLAGS, INIT_NO_DCLOAD, fs_dcload_shutdown);
	KOS_INIT_FLAG_NONE(OUR_FLAGS, INIT_NO_DCLOAD, arch_init_net_dcload_ip);
	KOS_INIT_FLAG(OUR_FLAGS, INIT_NO_DCLOAD, arch_init_net_no_dcload);
	KOS_INIT_FLAG(OUR_FLAGS, INIT_CDROM, cdrom_init);
	KOS_INIT_FLAG(OUR_FLAGS, INIT_CDROM, cdrom_shutdown);
	KOS_INIT_FLAG(OUR_FLAGS, INIT_CDROM, fs_iso9660_init);
	KOS_INIT_FLAG(OUR_FLAGS, INIT_CDROM, fs_iso9660_shutdown);
	KOS_INIT_FLAG(OUR_FLAGS, INIT_CONTROLLER, cont_init);
	KOS_INIT_FLAG(OUR_FLAGS, INIT_CONTROLLER, cont_shutdown);
	KOS_INIT_FLAG(OUR_FLAGS, INIT_KEYBOARD, kbd_init);
	KOS_INIT_FLAG(OUR_FLAGS, INIT_KEYBOARD, kbd_shutdown);
	KOS_INIT_FLAG(OUR_FLAGS, INIT_MOUSE, mouse_init);
	KOS_INIT_FLAG(OUR_FLAGS, INIT_MOUSE, mouse_shutdown);
	KOS_INIT_FLAG(OUR_FLAGS, INIT_LIGHTGUN, lightgun_init);
	KOS_INIT_FLAG(OUR_FLAGS, INIT_LIGHTGUN, lightgun_shutdown);
	KOS_INIT_FLAG(OUR_FLAGS, INIT_VMU, vmu_init);
	KOS_INIT_FLAG(OUR_FLAGS, INIT_VMU, vmu_shutdown);
	KOS_INIT_FLAG(OUR_FLAGS, INIT_VMU, vmu_fs_init);
	KOS_INIT_FLAG(OUR_FLAGS, INIT_VMU, vmu_fs_shutdown);
	KOS_INIT_FLAG(OUR_FLAGS, INIT_PURUPURU, purupuru_init);
	KOS_INIT_FLAG(OUR_FLAGS, INIT_PURUPURU, purupuru_shutdown);
	KOS_INIT_FLAG(OUR_FLAGS, INIT_SIP, sip_init);
	KOS_INIT_FLAG(OUR_FLAGS, INIT_SIP, sip_shutdown);
	KOS_INIT_FLAG(OUR_FLAGS, INIT_DREAMEYE, dreameye_init);
	KOS_INIT_FLAG(OUR_FLAGS, INIT_DREAMEYE, dreameye_shutdown);
	KOS_INIT_FLAG(OUR_FLAGS, INIT_MIE, mie_init);
	KOS_INIT_FLAG(OUR_FLAGS, INIT_MIE, mie_shutdown);
	KOS_INIT_FLAG(OUR_FLAGS, INIT_MIE, mie_init_scan);
	KOS_INIT_FLAG(OUR_FLAGS, INIT_MAPLE_ALL, maple_init);
	KOS_INIT_FLAG(OUR_FLAGS, INIT_MAPLE_ALL, maple_shutdown);
	/* END GENERATED */

/*
 *	The one line KOS would have emitted, inverted. `maple_wait_scan` is never
 *	called, so init never blocks on all four ports reporting.
 */
void (*maple_wait_scan_weak)(void) = NULL;

/*
 *	Bounded replacement for the scan wait.
 *
 *	The same predicate KOS uses -- `maple_state.scan_ready_mask == 0xf`, all four
 *	ports reported -- with a deadline on it. `maple_state` and the mask are both
 *	public in dc/maple.h, so this is KOS's own condition rather than a guess at
 *	one.
 *
 *	A normal boot leaves in a few frames and behaves exactly as it did before. A
 *	device that never answers costs the timeout instead of the console.
 *
 *	Returns 1 if the scan completed, 0 if it timed out. Neither is fatal: the mask
 *	falling short only means some port is unaccounted for, and the ports that did
 *	answer have already attached their devices.
 */
int dc_maple_wait_scan_bounded(unsigned int timeout_ms) {
	uint64_t deadline = timer_ms_gettime64() + timeout_ms;

	while (maple_state.scan_ready_mask != 0xf) {
		if (timer_ms_gettime64() >= deadline)
			return 0;

		/* Devices attach from the vblank handler, so yield rather than spin. */
		thd_pass();
	}

	return 1;
}
