#!/usr/bin/env python3
"""Regenerate the KOS init-flag list inside dc/dc_maple.c.

    python3 tools/gen-maple-flags.py

The port needs every subsystem KOS_INIT_FLAGS(INIT_DEFAULT) would start, except
`maple_wait_scan` -- an unbounded wait for all four maple ports that a rumble
pack turns into a boot hang. No combination of flags separates the two, because
INIT_MAPLE_ALL is the OR of eight peripheral flags and the gate is a bitwise AND.
So the list is emitted here instead, copied from KOS's own headers with that one
line dropped, and `maple_wait_scan_weak` defined NULL by hand in dc_maple.c.

Run this after updating KallistiOS. It rewrites only the region between the two
GENERATED markers, and fails loudly if KOS's list has changed shape.
"""
import os, re, sys

KOS  = os.environ.get('KOS_BASE', '/opt/toolchains/dc/kos')
HERE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DEST = os.path.join(HERE, 'dc', 'dc_maple.c')
BEGIN = '\t/* GENERATED by tools/gen-maple-flags.py -- do not hand-edit. */'
END   = '\t/* END GENERATED */'

# Only these forms are list entries. Anything else on a continuation line is
# documentation, and two doc lines happen to begin with "KOS_INIT_FLAGS".
ENTRY = re.compile(r'^(?:const uint32_t __kos_init_flags = \(flags\)'
                   r'|KOS_INIT_FLAG(?:_NONE|_ALL)?\(flags,\s*\w+,\s*\w+\))$')

def body(path, macro):
    src = open(path).read()
    m = re.search(r'#define\s+' + re.escape(macro) + r'\(flags\)((?:[^\n]*\\\n)*[^\n]*)', src)
    if not m:
        sys.exit(f'{macro} not found in {path}')
    out = []
    for line in m.group(1).split('\n'):
        line = line.strip().rstrip('\\').strip().rstrip(';')
        if ENTRY.match(line):
            out.append(line)
    return out

generic = body(os.path.join(KOS, 'include/kos/init.h'), '__KOS_INIT_FLAGS_0')
arch    = body(os.path.join(KOS, 'kernel/arch/dreamcast/include/arch/init_flags.h'),
               'KOS_INIT_FLAGS_ARCH')
entries = generic + arch

if not any('__kos_init_flags' in e for e in entries):
    sys.exit('the flag list no longer defines __kos_init_flags -- check KOS')
skipped = [e for e in entries if 'maple_wait_scan' in e]
if len(skipped) != 1:
    sys.exit(f'expected exactly one maple_wait_scan entry, found {len(skipped)}')
if not any('maple_init' in e for e in entries):
    sys.exit('maple_init is missing from the list -- refusing to write')

kept = [e for e in entries if 'maple_wait_scan' not in e]
lines = [BEGIN]
lines += ['\t' + e.replace('(flags,', '(OUR_FLAGS,').replace('(flags)', '(OUR_FLAGS)') + ';'
          for e in kept]
lines.append(END)

src = open(DEST).read()
new = re.sub(re.escape(BEGIN) + r'.*?' + re.escape(END), '\n'.join(lines), src, flags=re.S)
if new == src and BEGIN not in src:
    sys.exit(f'markers not found in {DEST}')
open(DEST, 'w').write(new)
print(f'{DEST}: {len(kept)} entries, skipped {skipped[0]}')
